# Generated by Django 4.1 on 2022-09-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('freq', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('ganre', models.CharField(max_length=50)),
            ],
        ),
    ]
