# Generated by Django 4.1 on 2022-09-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ganre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='ganre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Station.ganre'),
        ),
    ]
