# Generated by Django 4.1 on 2022-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_ganre_alter_station_ganre'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='icon',
            field=models.ImageField(default='none', upload_to='icons'),
        ),
        migrations.AddField(
            model_name='station',
            name='url_address',
            field=models.URLField(default='none'),
        ),
    ]
