# Generated by Django 4.1 on 2022-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_station_icon_station_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='freq',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
