# Generated by Django 4.1 on 2022-09-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0005_station_freq2_alter_station_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='freq2',
        ),
        migrations.AlterField(
            model_name='station',
            name='freq',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
