# Generated by Django 4.1 on 2022-09-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0006_remove_station_freq2_alter_station_freq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='freq',
            new_name='freq2',
        ),
    ]
