# Generated by Django 4.1 on 2022-09-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0007_rename_freq_station_freq2'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='freq',
            field=models.IntegerField(null=True),
        ),
    ]
