# Generated by Django 4.1 on 2022-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0008_station_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='freq2',
        ),
        migrations.AlterField(
            model_name='station',
            name='freq',
            field=models.IntegerField(default=8750, null=True),
        ),
    ]
