# Generated by Django 4.1 on 2022-09-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0009_remove_station_freq2_alter_station_freq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='freq',
        ),
    ]
