# Generated by Django 4.1 on 2022-09-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0010_remove_station_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='freq',
            field=models.DecimalField(decimal_places=2, default=87, max_digits=5, null=True),
        ),
    ]
